In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("/content/video_games_sales.csv")
df.head()

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rank         16598 non-null  int64
 1   name         16598 non-null  object
 2   platform     16598 non-null  object
 3   year         16327 non-null  float64
 4   genre        16598 non-null  object
 5   publisher    16540 non-null  object
 6   na_sales     16598 non-null  float64
 7   eu_sales     16598 non-null  float64
 8   jp_sales     16598 non-null  float64
 9   other_sales  16598 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.3+ MB

In [ ]:
df.describe()

,rank,year,na_sales,eu_sales,jp_sales,other_sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000

In [ ]:
df.isna().sum()

rank             0
name             0
platform         0
year           271
genre            0
publisher       58
na_sales         0
eu_sales         0
jp_sales         0
other_sales      0
dtype: int64

In [ ]:
# 3. Data Cleaning
# Drop rows with missing values
df.dropna(inplace=True)


# Remove non-useful column if present
if 'Name' in df.columns:
    df.drop('Name', axis=1, inplace=True)

In [ ]:
df.isna().sum()

rank           0
name           0
platform       0
year           0
genre          0
publisher      0
na_sales       0
eu_sales       0
jp_sales       0
other_sales    0
dtype: int64

In [ ]:
# 4. Encode Categorical Columns
label_encoder = LabelEncoder()

categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [ ]:
# 5. Feature & Target Selection
# X = df.drop('global_sales', axis=1)
# y = df['global_sales']
X = df[['platform', 'year', 'genre', 'publisher',
        'na_sales', 'eu_sales', 'jp_sales', 'other_sales']]
df['global_sales'] = df['na_sales'] + df['eu_sales'] + df['jp_sales'] + df['other_sales']
y = df['global_sales']

In [ ]:
# 6. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# 7. Train Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# 8. Predictions
y_pred = model.predict(X_test)

In [ ]:
df.head()

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,10849,26,2006.0,10,359,41.49,29.02,3.77,8.46,82.74
1,2,9201,11,1985.0,4,359,29.08,3.58,6.81,0.77,40.24
2,3,5493,26,2008.0,6,359,15.85,12.88,3.79,3.31,35.83
3,4,10851,26,2009.0,10,359,15.75,11.01,3.28,2.96,33.00
4,5,7247,5,1996.0,7,359,11.27,8.89,10.22,1.00,31.38

In [ ]:
# 9. Evaluation Metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R2 Score:", r2)

Mean Absolute Error (MAE): 1.6014118274175772e-15
Mean Squared Error (MSE): 1.0324336505992621e-29
Root Mean Squared Error (RMSE): 3.213150557629166e-15
R2 Score: 1.0

In [ ]:
import pickle
# Save model
with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

print("model.pkl saved successfully")

model.pkl saved successfully